name: Build README

on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_CODE: ${{ secrets.APP_CODE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8.6
        uses: actions/setup-python@v2
        with:
            python-version: '3.8.6'

      - name: Update README
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 update.py

      - name: Publish
        run: |
          git add .
          git config --global user.email "dukenan@163.com"
          git config --global user.name "shaun"
          git commit -m "update README,  $(date "+%a %b %d %H:%M %Z")" || echo "No changes to commit"
          git push