name: Build README

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_CODE: ${{ secrets.APP_CODE }}
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'
            cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        run: |
          chmod +x run.sh
          /bin/bash run.sh