name: Build README

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_CODE: ${{ secrets.APP_CODE }}
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8.6
        uses: actions/setup-python@v2
        with:
            python-version: '3.8.6'

      - name: Run Script
        run: |
          chmod +x run.sh
          /bin/bash run.sh